fixed bugs

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,46 +1,53 @@
-version: 2.1
+version: 2
 jobs:
-  format-violation:
+  build:
     docker:
-      - image: buildpack-deps:trusty
+      # - image: buildpack-deps:trusty
+      - image: cibuilds/hugo:latest
     environment:
       - TARGET_DIRS: "news|press-release"
+      - IMG_SIZE_LIMIT: "500000"
     steps:
       - checkout
       - run:
           name: Check directory structure
           shell: /bin/bash
+          when: always
           command: |
-            files=$(git diff --name-only --diff-filter=ACMR origin/master..HEAD -- '*.md' | grep -P "/contents/(${TARGET_DIRS})/")
+            files=$(git diff --name-only --diff-filter=ACMR origin/master..HEAD -- '*.md' | grep -P "content/(${TARGET_DIRS})/")
             [ -z "$files" ] && exit 0
-            [ -n "$(echo "$files" | grep -vP '/contents/(${TARGET_DIRS})/[0-9]{4}-[0-9]{2}-[0-9]{2}-[^/]+/index\.md$')" ] && exit 1
+            # if there is a filename which does NOT match the condition (grep -v), exit 1
+            [ -z "$(echo -n "$files" | grep -vP "content/(${TARGET_DIRS})/[0-9]{4}-[0-9]{2}-[0-9]{2}-[^/]+/index\.md$")" ]
+      - run:
+          name: Check filesize of images
+          shell: /bin/bash
+          when: always
+          command: |
+            files=$(git diff --name-only --diff-filter=ACMR origin/master..HEAD -- '*.jpg' '*.png' | grep -P "content/(${TARGET_DIRS})/")
+            [ -z "$files" ] && exit 0
+            [ "$(wc -c < "$files")" -lt $IMG_SIZE_LIMIT ]
       - run:
           name: Check title and summary field
           shell: /bin/bash
+          when: always
           command: |
-            files=$(git diff --name-only --diff-filter=ACMR origin/master..HEAD -- '*.md' | grep -P "(^|/)(${TARGET_DIRS})/")
+            files=$(git diff --name-only --diff-filter=ACMR origin/master..HEAD -- '*.md' | grep -P "content/(${TARGET_DIRS})/")
             [ -z "$files" ] && exit 0
             for file in $files ; do
-              if [ -z "$( cat "$file" | grep -oPz '\-{3}[\s\S]+?title:[\s\S]+?\-{3}' )" ] || [ -z "$(cat "$file" | grep -oPz '\-{3}[\s\S]+?summary:[\s\S]+?\-{3}')" ] ; then
-                echo 'Error: Either title or summary field is not satisfied!'
+              # grep options
+              # -o: show only nonempty parts of lines that match
+              # -P: PATTERNS are Perl regular expressions
+              # -z: a data line ends in 0 byte, not newline
+              # -a: assume that binary files are 'text'
+              if grep -oPzva '\-{3}[\s\S]+?title:[\s\S]+?\-{3}' "$file" || grep -oPzva '\-{3}[\s\S]+?summary:[\s\S]+?\-{3}' "$file" ; then
+                echo "Error: Either title or summary field is not satisfied on $file"
                 exit 1
               fi
             done
-  duplicate-url:
-    docker:
-      - image: cibuilds/hugo:latest
-    steps:
-      - checkout
       - run:
           name: Check duplicated URL
+          shell: /bin/bash
+          when: always
           command: |
-            [ -z "$(hugo -DEF --path-warnings --renderToMemory | grep -P 'WARN.*Duplicate target paths')" ]
-workflows:
-  version: 2
-  requirements:
-    jobs:
-      - format-violation
-  site-validity:
-    jobs:
-      - duplicate-url
+            hugo -DEF --path-warnings --renderToMemory | ! grep -P 'WARN.*Duplicate target paths')"
 
