added dir structure check

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,12 +1,22 @@
 version: 2.1
 jobs:
-  frontmatter-violation:
+  format-violation:
     docker:
       - image: buildpack-deps:trusty
     environment:
       - TARGET_DIRS: "news|press-release"
     steps:
       - checkout
+      - run:
+          name: Check directory structure
+          shell: /bin/bash
+          command: |
+            files=$(git diff --name-only --diff-filter=ACMR origin/master..HEAD -- '*.md' | grep -P "(^|/)(${TARGET_DIRS})/")
+            [ -z "$files" ] && exit 0
+            if [ -z "$(echo "$files" | grep -vP '/[0-9]{4}-[0-9]{2}-[0-9]{2}-[^/]+/index\.md$') ] ; then
+              echo 'Error: Directory structure incorrect'
+              exit 1
+            fi
       - run:
           name: Check title and summary field
           shell: /bin/bash
@@ -32,7 +42,7 @@ workflows:
   version: 2
   requirements:
     jobs:
-      - frontmatter-violation
+      - format-violation
   site-validity:
     jobs:
       - duplicate-url
